#!/bin/bash

username='dan@blueprintapparelcompany.com'
password='Luckycharms1112'
userPoolId='us-east-1_XNOWDtwOR'
appClientId='4ogalcsrqvq8m55jgllibui8gt'
cognitoRegion='us-east-1'
identityPoolId='us-east-1:22e886ad-2c19-436e-9fcd-9495ed484f3c'
invokeUrl='https://er3n6mlsxd.execute-api.us-east-1.amazonaws.com/prod'
apiGatewayRegion='us-east-1'
pathTemplate='/mockupgenerator/{itemId}'
method='GET'
body='{}'
params='{"itemId":"Jerzees"}'
npx aws-api-gateway-cli-test \
--username=${username} \
--password=${password} \
--user-pool-id=${userPoolId}  \
--app-client-id=${appClientId} \
--cognito-region=${cognitoRegion} \
--identity-pool-id=${identityPoolId} \
--invoke-url=${invokeUrl} \
--api-gateway-region=${apiGatewayRegion} \
--path-template=${pathTemplate} \
--method=${method} \
--body=${body} \
--params=${params}
